### ISSUE TITLE
Looking for Android auto 

### ISSUE THREAD

**Issue by alexplayzzz** [nisargjhaveri/AAWirelessDongle#24]
Since my interest in this project, at first I was wondering to run this in arm but due to board compability & your feedback I planned on ordering a raspberry Pi zero w, I flashed the img into sd & all the process done once I start the device I connect to the Bluetooth sometimes it doesn't connect to the wifi & if connected it still loops on with notification looking for Android auto device which is annoying I tried it with head unit of Suzuki Scross & Head unit reloaded tell me if I am doing any mistakes

**Comment by alexplayzzz** [comment]
It doesn't connect to wifi & keeps saying looking for Android auto I am using pixel 6a

**Comment by alexplayzzz** [comment]
![IMG-20231203-WA0003](https://github.com/nisargjhaveri/AAWirelessDongle/assets/81725685/0062c710-9285-4a5a-bc07-0702e5e12247)
![Screenshot_20231203-213448_Settings](https://github.com/nisargjhaveri/AAWirelessDongle/assets/81725685/50490c8f-33fd-4afb-ad41-1eaeb119fab9)

**Comment by nisargjhaveri** [comment]
Seems like the wifi connected fine from the screenshot, but the AA is not able to connect. My hunch is that, this happens because the headunit timeouts before the wifi connects.

**Comment by nisargjhaveri** [comment]
You can try out the builds from #25 if it helps in this case. I've attempted to work around the timeout by establishing AA communication early with the headunit.

**Comment by alexplayzzz** [comment]
I found a better way to fix it I powered the raspberry by the ciggerate port of the car which turns on before turning on headunit & it matches the connection time & in the same interval head unit boots up
