### ISSUE TITLE
Does it not work on Raspberry Pi 3 B+?

### ISSUE THREAD

**Issue by namsa87** [nisargjhaveri/AAWirelessDongle#40]
I have a Raspberry Pi 3 B+.
I downloaded the image file, installed it on the Raspberry Pi, and booted it, but there was no response when connected to the car.
So, I looked it up and found that the device in question does not have OTG mode. Is this correct information?
Is there any solution?

**Comment by nisargjhaveri** [comment]
You're correct, Raspberry Pi 3 B+ does not support OTG or USB gadget mode. I don't think there is anything much we can do about that. You will need to use one of the other supported devices.
