### ISSUE TITLE
Using for Tata Nexon 2023 edition - Audio Music Lag when using touchscreen.

### ISSUE THREAD

**Issue by mddanish** [nisargjhaveri/AAWirelessDongle#43]
Welldone for creating a very usefull and money saving project.
I'm using it with my RPi0-W, connect very nicesly and good.

The only problem I noticed when Music is playing & streaming to car infotainment, and when using Car touchscreen to navigate or use map to set, Audio starts lagging.

Using this saved me 8K for devices available on amazon.

**Comment by Ioniq3** [comment]
Hello mddanish,

If this help you, I have the same RPI0W and after disable the hdmi output the performance increases, so the hdmi drains a lot of energy of the board.
It is done add the following line in the config.txt 

hdmi_blanking=1

**Comment by mddanish** [comment]
Thanks Mate, it works

**Comment by gamelaster** [comment]
@nisargjhaveri wouldn't be good to disable hdmi by default?

**Comment by nisargjhaveri** [comment]
Should be fixed by #48.
