### ISSUE TITLE
Bluetooth is not available

### ISSUE THREAD

**Issue by danihidayatx** [nisargjhaveri/AAWirelessDongle#5]
hello,

i build it using my raspberry pi 4, the wifi is available but the bluetooth is not even discovered. so im reflashing using your release instead of building. but got the same result instead
![WhatsApp Image 2023-10-20 at 11 03 00 (1)](https://github.com/nisargjhaveri/AAWirelessDongle/assets/148239387/d89a849e-8c26-4440-be01-1457fc3fbaa7)
![WhatsApp Image 2023-10-20 at 11 03 00](https://github.com/nisargjhaveri/AAWirelessDongle/assets/148239387/77d4c2ff-af26-429d-b1fd-cdd4b19ff42d)

**Comment by nisargjhaveri** [comment]
Bluetooth is only available when Android Auto is attempted from the head unit. Also, it is discoverable for around 3 minutes by default. You can have a look if your headunit is starting the Android Auto connection via usb or not. If not, we may have to find another approach on how to make it work.

**Comment by danihidayatx** [comment]
yes, i look into autostart script. im testing on hyundai ioniq 5 and it's
not working although it's working on mercedes head unit.

for ioniq im gonna debug it further

thanks

Pada Min, 22 Okt 2023 20.32, Nisarg Jhaveri ***@***.***>
menulis:

**Comment by danihidayatx** [comment]
need further test
