### ISSUE TITLE
Question: Compatibility of AAWireless with stock Pi OS

### ISSUE THREAD

**Issue by JazzzzX** [nisargjhaveri/AAWirelessDongle#51]
Hello,

I'm interested in learning whether the AAWirelessDongle is compatible with a standard Raspberry Pi OS image. If so, are there specific installation procedures or packages required? If possible a compilation wiki for it will be helpfull

**Comment by nisargjhaveri** [comment]
We do need some kernel modifications for the android accessory driver to work. This would makes it difficult to get it working on the stock Raspberry Pi OS.

**Comment by JazzzzX** [comment]
I can understand, Thanks
