### ISSUE TITLE
 Inquiry regarding Bluetooth reconnection

### ISSUE THREAD

**Issue by namsa87** [nisargjhaveri/AAWirelessDongle#53]
If the Bluetooth connection is lost, doesn't it automatically re-scan? It is unfortunate that once it is disconnected, it cannot be reconnected.

**Comment by namsa87** [comment]
It's the same symptom.
When the smartphone and dongle are paired, the connection switches to Wi-Fi and the Bluetooth connection is disconnected. And if the Wi-Fi connection is lost while going outside for a while, the Bluetooth and dongle need to be repaired, but nothing happens. However, if you kill aawgd and run it again, it will be repaired and reconnected.

**Comment by nisargjhaveri** [comment]
Thanks! Let's continue the conversation as part of #26 in that case.
